In [4]:
%pip install torch 
import torch
print (torch.__version__)
print (torch.cuda.is_available())

Note: you may need to restart the kernel to use updated packages.
2.14.0+cpu
False


In [ ]:
import torch

# طرق إنشاء tensor
a = torch.tensor([1, 2, 3])              # create tensor from a list
b = torch.zeros(3, 4)                    # matrix of zeros
c = torch.ones(2, 2)                     # matrix of ones
d = torch.rand(3, 3)                     # random numbers 
e = torch.randn(3, 3)                    # random numbers from normal distribution

print(a.shape)      #  (dimensions)
print(a.dtype)      # (data type)
print(a.device)     # (device type) cpu or gpu

torch.Size([3])
torch.int64
cpu


In [ ]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

print(x + y)          # summation x and y
print(x * y)          # maultiplication
print(x @ y)          # (dot product)
print(x.sum())        # sumation
print(x.mean())       # calculating the mean
print(x.reshape(3,1)) #reshaping the tensor to 3 rows and 1 column

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor(32.)
tensor(6.)
tensor(2.)
tensor([[1.],
        [2.],
        [3.]])


In [9]:
#convert from cpu to gpu very important in deep learning
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.tensor([1.0, 2.0, 3.0])
x = x.to(device)  #transfer tensor to gpu if gpu available

In [ ]:
w = torch.tensor(0.5, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)
x = torch.tensor(2.0)
y_true = torch.tensor(5.0)

y_pred = w * x + b
loss = (y_pred - y_true) ** 2   # Squared error

loss.backward()
print(w.grad)   # how much changing w will affect the loss
print(b.grad)   # how much changing b will affect the loss
#this happens in any nueral network but you make this on billions of parameters 

tensor(-16.)
tensor(-8.)


In [21]:
"""
how i can built Neural Network Model in pytorch
every neural network model in pytorch is a class that inherits from nn.Module:
__init__=> method is used to define the layers of the model
forward => method is used to define the forward pass of the model
let me give you an example
"""
import torch
import torch.nn as nn 

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(1, 10) # one input and 10 output
        self.layer2 = nn.Linear(10, 32) # 10 inputs and 32 outputs
        self.layer3 = nn.Linear(32, 16) # 32 inputs and 16 outputs
        self.layer4 = nn.Linear(16, 1) # 16 inputs and 1 output
        self.relu = nn.ReLU() # activation function

    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        x = self.layer2(x)
        x = torch.relu(x)
        x = self.layer3(x)
        x = torch.relu(x)
        x = self.layer4(x)
        return x
model = NeuralNetwork()

# Input
x = torch.tensor([[5.0]])

# True value
y_true = torch.tensor([[0.04]])

# Loss
loss_fn = nn.MSELoss()

# Forward Pass
predictions = model(x)

# Calculate Loss
loss = loss_fn(predictions, y_true)

print("Prediction:", predictions)
print("True value:", y_true)
print("Loss:", loss.item())


Prediction: tensor([[0.1871]], grad_fn=<AddmmBackward0>)
True value: tensor([[0.0400]])
Loss: 0.021649818867444992


In [22]:
""" nn.Linear(in_features, out_features)      # طبقة Dense
nn.Conv2d(in_channels, out_channels, kernel_size)  # طبقة Convolution (للصور)
nn.MaxPool2d(kernel_size)                 # تقليل حجم الصورة
nn.ReLU()                                 # activation
nn.Sigmoid()                              # activation (بين 0 و1، للـ binary classification)
nn.Softmax(dim=1)                         # activation (لتوزيع احتمالات، للـ multi-class)
nn.Dropout(p=0.5)                         # regularization
nn.BatchNorm1d(num_features)              # regularization/تثبيت"""
# Loss functions

loss_fn = nn.MSELoss()          # Mean Squared Error (لـ regression)
loss_fn = nn.CrossEntropyLoss() # Cross Entropy (لـ multi-class classification) 
loss_fn = nn.BCELoss()         # Binary Cross Entropy (لـ binary classification)

predictions = model (x)
loss = loss_fn(predictions, y_true)

print (loss.item())  # loss value as a float

0.2659432888031006


In [23]:
import torch.optim as optim

optimizer = optim.SGD(model.parameters(), lr=0.01)
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [ ]:
model = NeuralNetwork()
loss_fn = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

num_epochs = 20

for epoch in range(num_epochs):
    model.train()   # وضع التدريب (يفعّل Dropout, BatchNorm...)

    # 1. Forward pass
    prediction = model(X_train)

    # 2. حساب الـ Loss
    loss = loss_fn(prediction, y_train)

    # 3. تصفير الـ gradients القديمة (مهم جداً!)
    optimizer.zero_grad()

    # 4. Backward pass (حساب الـ gradients)
    loss.backward()

    # 5. تحديث الأوزان
    optimizer.step()

    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item():.4f}")